name: 构建并发布Docker镜像

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: 检查代码
        uses: actions/checkout@v4

      - name: 登录 GitHub 镜像仓库
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 设置 Docker Buildx (缓存需要)
        uses: docker/setup-buildx-action@v3

      - name: 构建并推送到 GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false

      - name: 清理旧版本镜像
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'vue-idle-xiuxian'
          package-type: 'container'
          min-versions-to-keep: 0
          delete-only-untagged-versions: 'true'